### ISSUE TITLE
Does not work with Remote - Container extension

### ISSUE THREAD

**Issue by AngellusMortis** [monovaldes/vscode-linter-codeclimate#4]
So I am using the new [Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) feature and I cannot get `linter-codeclimate` to work inside of a Docker container using the [Remote - Container extension](https://code.visualstudio.com/docs/remote/containers).

How everything is set up:

* `/var/run/docker.sock` is mounted from my local machine into my docker container.
* The `codeclimate` is installed
* I have the `$CODECLIMATE_CODE` set globally in my `docker-compose.yml` to point to the real path to the code.
* `linter-codeclimate` is installed inside of the Docker container (shows up in the Extensions tab and everything)
* `linter_codeclimate.enabled` is set to `true`

I am able to do `codeclimate anaylze path/to.py` and it works fine from the integrated terminal, but it will not seem to work from the VS Code extension. I am also not able to find any logs for the extension as well, so I cannot figure out what command it is trying to run or even if it has the correct `$CODECLIMATE_CODE` environment variable. 

I have also verified the extension work perfectly outside of Docker.

**Comment by monovaldes** [comment]
Hi @AngellusMortis ,
I haven't worked with the new extension yet, probably the exec_path and spawn command are calculated and run locally instead of remotely?
referenced lines:
- https://github.com/monovaldes/vscode-linter-codeclimate/blob/master/src/codeclimate.ts#L72 
- https://github.com/monovaldes/vscode-linter-codeclimate/blob/master/src/codeclimate.ts#L76

A fix could be:
- knowing the the remote container name (through the extension, maybe?)
- knowing the relative path from ~ContainerHome to ~Filepath
- spawn a docker exec command, which in itself calls later codeclimate analyze

Feel free to fork the project and propose a solution.

Best regards.

**Comment by AngellusMortis** [comment]
> calculated and run locally instead of remotely? 

I do not think it is. The extension actually gets install inside of the Docker container. It should not know anything about the original host (that is why I have to set the `$CODECLIMATE_CODE` because the Code Climate container actually runs on the original host).  

It works great with the Remote - SSH variant, it just has an issue with the Remote - Containers variant of the Remote Development stuff. 

> Feel free to fork the project and propose a solution. 

I would love to, but I am not the best with Javascript and I have never used TypeScript.

**Comment by AngellusMortis** [comment]
I managed to figure it out. See #5

**Comment by monovaldes** [comment]
Fix merged and published, thanks!
